


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

encrypt:
  # DB/ES
  type: DB
  # DB
  dbChunk: 2
  esUrl: 127.0.0.1:9200
  indexName: encrypt