


spring:
  datasource:
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://192.168.160.112:5236/ZUIYU
    username: ZUIYU
    password: 1234567890
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

encrypt:
  # DB/ES
  type: ES
  # DB
  dbChunk: 2
  esUrl: 127.0.0.1:9200
  indexName: encrypt